#Seed contains 1 admin, 1 moderator, 5 authors, 12 articles, and 12 comments
#All passwords are 'password'
User.create(first_name: 'admin', last_name: 'admin', role: 'admin', email: "admin@yahoo.com" password: 'password')
hank = User.create(first_name: 'Hank', last_name: 'Hill', role: 'moderator', email: 'hank@yahoo.com', password: 'password')

john = User.create(first_name: 'John', last_name: 'Doe', role: 'author', email: 'john@yahoo.com', password: 'password')
jane = User.create(first_name: 'Jane', last_name: 'Doe', role: 'author', email: 'jane@yahoo.com', password: 'password')
lenny = User.create(first_name: 'Lenny', last_name: 'Leonard', role: 'author', email: 'lenny@yahoo.com', password: 'password')
carl = User.create(first_name: 'Carl', last_name: 'Carlson', role: 'author', email: 'carl@yahoo.com', password: 'password')
homer = User.create(first_name: 'Homer', last_name: 'Simpson', role: 'author', email: 'homer@yahoo.com', password: 'password')

cat = Article.create(title: 'My Cat Mittens Knocked Something Over Again', author: 'John Doe', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut fermentum mauris ut aliquet condimentum. Nullam lectus odio, lobortis a mauris non, viverra viverra lectus. Vivamus bibendum orci non vestibulum ornare. Donec eget erat risus. Integer commodo nisl massa, at bibendum ligula luctus quis. Aenean purus lacus, vestibulum vel eros vel, ornare rhoncus dolor. Mauris eget sapien vel leo imperdiet fermentum nec et ex. Fusce eget risus at justo mollis faucibus. Nullam luctus nulla quis odio volutpat varius.

Phasellus ante ante, gravida et nulla eu, tempor dictum sem. Duis tempus ipsum ac lectus laoreet consectetur. Integer at maximus arcu. Donec nulla ante, ornare rhoncus ullamcorper sed, malesuada pharetra turpis. Curabitur ultricies velit ac lectus pharetra sagittis. Vestibulum gravida mi ac tincidunt pulvinar. Suspendisse suscipit, massa at vestibulum tempor, nisl erat iaculis turpis, non maximus neque erat at velit. Vestibulum est lacus, maximus vel pellentesque et, varius quis mi. Mauris sed quam ac nunc lacinia congue.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse a tortor a mauris luctus finibus eu sed mi. Integer scelerisque aliquam orci quis viverra. Nunc lobortis viverra semper. Curabitur hendrerit elit eget congue tincidunt. Curabitur sagittis blandit ex sed tincidunt. Nullam tellus diam, posuere at viverra a, varius sed nisi. In vel egestas nibh.', user_id: john.id)

dog = Article.create(title: 'My Dog Spot', author: 'Jane Doe', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut fermentum mauris ut aliquet condimentum. Nullam lectus odio, lobortis a mauris non, viverra viverra lectus. Vivamus bibendum orci non vestibulum ornare. Donec eget erat risus. Integer commodo nisl massa, at bibendum ligula luctus quis. Aenean purus lacus, vestibulum vel eros vel, ornare rhoncus dolor. Mauris eget sapien vel leo imperdiet fermentum nec et ex. Fusce eget risus at justo mollis faucibus. Nullam luctus nulla quis odio volutpat varius.

Phasellus ante ante, gravida et nulla eu, tempor dictum sem. Duis tempus ipsum ac lectus laoreet consectetur. Integer at maximus arcu. Donec nulla ante, ornare rhoncus ullamcorper sed, malesuada pharetra turpis. Curabitur ultricies velit ac lectus pharetra sagittis. Vestibulum gravida mi ac tincidunt pulvinar. Suspendisse suscipit, massa at vestibulum tempor, nisl erat iaculis turpis, non maximus neque erat at velit. Vestibulum est lacus, maximus vel pellentesque et, varius quis mi. Mauris sed quam ac nunc lacinia congue.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse a tortor a mauris luctus finibus eu sed mi. Integer scelerisque aliquam orci quis viverra. Nunc lobortis viverra semper. Curabitur hendrerit elit eget congue tincidunt. Curabitur sagittis blandit ex sed tincidunt. Nullam tellus diam, posuere at viverra a, varius sed nisi. In vel egestas nibh.', user_id: jane.id)

mail = Article.create(title: 'The Post Office Is Not That Bad', author: 'Lenny Leanard', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut fermentum mauris ut aliquet condimentum. Nullam lectus odio, lobortis a mauris non, viverra viverra lectus. Vivamus bibendum orci non vestibulum ornare. Donec eget erat risus. Integer commodo nisl massa, at bibendum ligula luctus quis. Aenean purus lacus, vestibulum vel eros vel, ornare rhoncus dolor. Mauris eget sapien vel leo imperdiet fermentum nec et ex. Fusce eget risus at justo mollis faucibus. Nullam luctus nulla quis odio volutpat varius.

Phasellus ante ante, gravida et nulla eu, tempor dictum sem. Duis tempus ipsum ac lectus laoreet consectetur. Integer at maximus arcu. Donec nulla ante, ornare rhoncus ullamcorper sed, malesuada pharetra turpis. Curabitur ultricies velit ac lectus pharetra sagittis. Vestibulum gravida mi ac tincidunt pulvinar. Suspendisse suscipit, massa at vestibulum tempor, nisl erat iaculis turpis, non maximus neque erat at velit. Vestibulum est lacus, maximus vel pellentesque et, varius quis mi. Mauris sed quam ac nunc lacinia congue.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse a tortor a mauris luctus finibus eu sed mi. Integer scelerisque aliquam orci quis viverra. Nunc lobortis viverra semper. Curabitur hendrerit elit eget congue tincidunt. Curabitur sagittis blandit ex sed tincidunt. Nullam tellus diam, posuere at viverra a, varius sed nisi. In vel egestas nibh.', user_id: lenny.id)

talk = Article.create(title: "This Is Why I Don't Talk Much", author: 'Carl Carlson', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut fermentum mauris ut aliquet condimentum. Nullam lectus odio, lobortis a mauris non, viverra viverra lectus. Vivamus bibendum orci non vestibulum ornare. Donec eget erat risus. Integer commodo nisl massa, at bibendum ligula luctus quis. Aenean purus lacus, vestibulum vel eros vel, ornare rhoncus dolor. Mauris eget sapien vel leo imperdiet fermentum nec et ex. Fusce eget risus at justo mollis faucibus. Nullam luctus nulla quis odio volutpat varius.

Phasellus ante ante, gravida et nulla eu, tempor dictum sem. Duis tempus ipsum ac lectus laoreet consectetur. Integer at maximus arcu. Donec nulla ante, ornare rhoncus ullamcorper sed, malesuada pharetra turpis. Curabitur ultricies velit ac lectus pharetra sagittis. Vestibulum gravida mi ac tincidunt pulvinar. Suspendisse suscipit, massa at vestibulum tempor, nisl erat iaculis turpis, non maximus neque erat at velit. Vestibulum est lacus, maximus vel pellentesque et, varius quis mi. Mauris sed quam ac nunc lacinia congue.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse a tortor a mauris luctus finibus eu sed mi. Integer scelerisque aliquam orci quis viverra. Nunc lobortis viverra semper. Curabitur hendrerit elit eget congue tincidunt. Curabitur sagittis blandit ex sed tincidunt. Nullam tellus diam, posuere at viverra a, varius sed nisi. In vel egestas nibh.', user_id: carl.id)

pants = Article.create(title: "Blue Pants", author: 'Homer Simpson', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut fermentum mauris ut aliquet condimentum. Nullam lectus odio, lobortis a mauris non, viverra viverra lectus. Vivamus bibendum orci non vestibulum ornare. Donec eget erat risus. Integer commodo nisl massa, at bibendum ligula luctus quis. Aenean purus lacus, vestibulum vel eros vel, ornare rhoncus dolor. Mauris eget sapien vel leo imperdiet fermentum nec et ex. Fusce eget risus at justo mollis faucibus. Nullam luctus nulla quis odio volutpat varius.

Phasellus ante ante, gravida et nulla eu, tempor dictum sem. Duis tempus ipsum ac lectus laoreet consectetur. Integer at maximus arcu. Donec nulla ante, ornare rhoncus ullamcorper sed, malesuada pharetra turpis. Curabitur ultricies velit ac lectus pharetra sagittis. Vestibulum gravida mi ac tincidunt pulvinar. Suspendisse suscipit, massa at vestibulum tempor, nisl erat iaculis turpis, non maximus neque erat at velit. Vestibulum est lacus, maximus vel pellentesque et, varius quis mi. Mauris sed quam ac nunc lacinia congue.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse a tortor a mauris luctus finibus eu sed mi. Integer scelerisque aliquam orci quis viverra. Nunc lobortis viverra semper. Curabitur hendrerit elit eget congue tincidunt. Curabitur sagittis blandit ex sed tincidunt. Nullam tellus diam, posuere at viverra a, varius sed nisi. In vel egestas nibh.', user_id: homer.id)

monorail = Article.create(title: "Achiving Your Dream Of Becoming A Monorail Conductor", author: 'Homer Simpson', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut fermentum mauris ut aliquet condimentum. Nullam lectus odio, lobortis a mauris non, viverra viverra lectus. Vivamus bibendum orci non vestibulum ornare. Donec eget erat risus. Integer commodo nisl massa, at bibendum ligula luctus quis. Aenean purus lacus, vestibulum vel eros vel, ornare rhoncus dolor. Mauris eget sapien vel leo imperdiet fermentum nec et ex. Fusce eget risus at justo mollis faucibus. Nullam luctus nulla quis odio volutpat varius.

Phasellus ante ante, gravida et nulla eu, tempor dictum sem. Duis tempus ipsum ac lectus laoreet consectetur. Integer at maximus arcu. Donec nulla ante, ornare rhoncus ullamcorper sed, malesuada pharetra turpis. Curabitur ultricies velit ac lectus pharetra sagittis. Vestibulum gravida mi ac tincidunt pulvinar. Suspendisse suscipit, massa at vestibulum tempor, nisl erat iaculis turpis, non maximus neque erat at velit. Vestibulum est lacus, maximus vel pellentesque et, varius quis mi. Mauris sed quam ac nunc lacinia congue.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse a tortor a mauris luctus finibus eu sed mi. Integer scelerisque aliquam orci quis viverra. Nunc lobortis viverra semper. Curabitur hendrerit elit eget congue tincidunt. Curabitur sagittis blandit ex sed tincidunt. Nullam tellus diam, posuere at viverra a, varius sed nisi. In vel egestas nibh.', user_id: homer.id)

propane = Article.create(title: "The Benefits Of Propane And Propane Accessories", author: 'Hank Hill', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut fermentum mauris ut aliquet condimentum. Nullam lectus odio, lobortis a mauris non, viverra viverra lectus. Vivamus bibendum orci non vestibulum ornare. Donec eget erat risus. Integer commodo nisl massa, at bibendum ligula luctus quis. Aenean purus lacus, vestibulum vel eros vel, ornare rhoncus dolor. Mauris eget sapien vel leo imperdiet fermentum nec et ex. Fusce eget risus at justo mollis faucibus. Nullam luctus nulla quis odio volutpat varius.

Phasellus ante ante, gravida et nulla eu, tempor dictum sem. Duis tempus ipsum ac lectus laoreet consectetur. Integer at maximus arcu. Donec nulla ante, ornare rhoncus ullamcorper sed, malesuada pharetra turpis. Curabitur ultricies velit ac lectus pharetra sagittis. Vestibulum gravida mi ac tincidunt pulvinar. Suspendisse suscipit, massa at vestibulum tempor, nisl erat iaculis turpis, non maximus neque erat at velit. Vestibulum est lacus, maximus vel pellentesque et, varius quis mi. Mauris sed quam ac nunc lacinia congue.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse a tortor a mauris luctus finibus eu sed mi. Integer scelerisque aliquam orci quis viverra. Nunc lobortis viverra semper. Curabitur hendrerit elit eget congue tincidunt. Curabitur sagittis blandit ex sed tincidunt. Nullam tellus diam, posuere at viverra a, varius sed nisi. In vel egestas nibh.', user_id: hank.id)

boy = Article.create(title: "10 Signs That Your Boy Ain't Right", author: 'Hank Hill', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut fermentum mauris ut aliquet condimentum. Nullam lectus odio, lobortis a mauris non, viverra viverra lectus. Vivamus bibendum orci non vestibulum ornare. Donec eget erat risus. Integer commodo nisl massa, at bibendum ligula luctus quis. Aenean purus lacus, vestibulum vel eros vel, ornare rhoncus dolor. Mauris eget sapien vel leo imperdiet fermentum nec et ex. Fusce eget risus at justo mollis faucibus. Nullam luctus nulla quis odio volutpat varius.

Phasellus ante ante, gravida et nulla eu, tempor dictum sem. Duis tempus ipsum ac lectus laoreet consectetur. Integer at maximus arcu. Donec nulla ante, ornare rhoncus ullamcorper sed, malesuada pharetra turpis. Curabitur ultricies velit ac lectus pharetra sagittis. Vestibulum gravida mi ac tincidunt pulvinar. Suspendisse suscipit, massa at vestibulum tempor, nisl erat iaculis turpis, non maximus neque erat at velit. Vestibulum est lacus, maximus vel pellentesque et, varius quis mi. Mauris sed quam ac nunc lacinia congue.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse a tortor a mauris luctus finibus eu sed mi. Integer scelerisque aliquam orci quis viverra. Nunc lobortis viverra semper. Curabitur hendrerit elit eget congue tincidunt. Curabitur sagittis blandit ex sed tincidunt. Nullam tellus diam, posuere at viverra a, varius sed nisi. In vel egestas nibh.', user_id: hank.id)

music = Article.create(title: "That Is Not Music", author: 'Hank Hill', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut fermentum mauris ut aliquet condimentum. Nullam lectus odio, lobortis a mauris non, viverra viverra lectus. Vivamus bibendum orci non vestibulum ornare. Donec eget erat risus. Integer commodo nisl massa, at bibendum ligula luctus quis. Aenean purus lacus, vestibulum vel eros vel, ornare rhoncus dolor. Mauris eget sapien vel leo imperdiet fermentum nec et ex. Fusce eget risus at justo mollis faucibus. Nullam luctus nulla quis odio volutpat varius.

Phasellus ante ante, gravida et nulla eu, tempor dictum sem. Duis tempus ipsum ac lectus laoreet consectetur. Integer at maximus arcu. Donec nulla ante, ornare rhoncus ullamcorper sed, malesuada pharetra turpis. Curabitur ultricies velit ac lectus pharetra sagittis. Vestibulum gravida mi ac tincidunt pulvinar. Suspendisse suscipit, massa at vestibulum tempor, nisl erat iaculis turpis, non maximus neque erat at velit. Vestibulum est lacus, maximus vel pellentesque et, varius quis mi. Mauris sed quam ac nunc lacinia congue.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse a tortor a mauris luctus finibus eu sed mi. Integer scelerisque aliquam orci quis viverra. Nunc lobortis viverra semper. Curabitur hendrerit elit eget congue tincidunt. Curabitur sagittis blandit ex sed tincidunt. Nullam tellus diam, posuere at viverra a, varius sed nisi. In vel egestas nibh.', user_id: hank.id)

english = Article.create(title: "Who Needs English, I'm Never Going To England", author: 'Homer Simpson', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut fermentum mauris ut aliquet condimentum. Nullam lectus odio, lobortis a mauris non, viverra viverra lectus. Vivamus bibendum orci non vestibulum ornare. Donec eget erat risus. Integer commodo nisl massa, at bibendum ligula luctus quis. Aenean purus lacus, vestibulum vel eros vel, ornare rhoncus dolor. Mauris eget sapien vel leo imperdiet fermentum nec et ex. Fusce eget risus at justo mollis faucibus. Nullam luctus nulla quis odio volutpat varius.

Phasellus ante ante, gravida et nulla eu, tempor dictum sem. Duis tempus ipsum ac lectus laoreet consectetur. Integer at maximus arcu. Donec nulla ante, ornare rhoncus ullamcorper sed, malesuada pharetra turpis. Curabitur ultricies velit ac lectus pharetra sagittis. Vestibulum gravida mi ac tincidunt pulvinar. Suspendisse suscipit, massa at vestibulum tempor, nisl erat iaculis turpis, non maximus neque erat at velit. Vestibulum est lacus, maximus vel pellentesque et, varius quis mi. Mauris sed quam ac nunc lacinia congue.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse a tortor a mauris luctus finibus eu sed mi. Integer scelerisque aliquam orci quis viverra. Nunc lobortis viverra semper. Curabitur hendrerit elit eget congue tincidunt. Curabitur sagittis blandit ex sed tincidunt. Nullam tellus diam, posuere at viverra a, varius sed nisi. In vel egestas nibh.', user_id: homer.id)

thermodynamics = Article.create(title: "In This House We Obey The Laws Of Thermodynamics!", author: 'Homer Simpson', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut fermentum mauris ut aliquet condimentum. Nullam lectus odio, lobortis a mauris non, viverra viverra lectus. Vivamus bibendum orci non vestibulum ornare. Donec eget erat risus. Integer commodo nisl massa, at bibendum ligula luctus quis. Aenean purus lacus, vestibulum vel eros vel, ornare rhoncus dolor. Mauris eget sapien vel leo imperdiet fermentum nec et ex. Fusce eget risus at justo mollis faucibus. Nullam luctus nulla quis odio volutpat varius.

Phasellus ante ante, gravida et nulla eu, tempor dictum sem. Duis tempus ipsum ac lectus laoreet consectetur. Integer at maximus arcu. Donec nulla ante, ornare rhoncus ullamcorper sed, malesuada pharetra turpis. Curabitur ultricies velit ac lectus pharetra sagittis. Vestibulum gravida mi ac tincidunt pulvinar. Suspendisse suscipit, massa at vestibulum tempor, nisl erat iaculis turpis, non maximus neque erat at velit. Vestibulum est lacus, maximus vel pellentesque et, varius quis mi. Mauris sed quam ac nunc lacinia congue.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse a tortor a mauris luctus finibus eu sed mi. Integer scelerisque aliquam orci quis viverra. Nunc lobortis viverra semper. Curabitur hendrerit elit eget congue tincidunt. Curabitur sagittis blandit ex sed tincidunt. Nullam tellus diam, posuere at viverra a, varius sed nisi. In vel egestas nibh.', user_id: homer.id)

internet = Article.create(title: "The Internet? Is That Thing Still Around", author: 'Homer Simpson', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut fermentum mauris ut aliquet condimentum. Nullam lectus odio, lobortis a mauris non, viverra viverra lectus. Vivamus bibendum orci non vestibulum ornare. Donec eget erat risus. Integer commodo nisl massa, at bibendum ligula luctus quis. Aenean purus lacus, vestibulum vel eros vel, ornare rhoncus dolor. Mauris eget sapien vel leo imperdiet fermentum nec et ex. Fusce eget risus at justo mollis faucibus. Nullam luctus nulla quis odio volutpat varius.

Phasellus ante ante, gravida et nulla eu, tempor dictum sem. Duis tempus ipsum ac lectus laoreet consectetur. Integer at maximus arcu. Donec nulla ante, ornare rhoncus ullamcorper sed, malesuada pharetra turpis. Curabitur ultricies velit ac lectus pharetra sagittis. Vestibulum gravida mi ac tincidunt pulvinar. Suspendisse suscipit, massa at vestibulum tempor, nisl erat iaculis turpis, non maximus neque erat at velit. Vestibulum est lacus, maximus vel pellentesque et, varius quis mi. Mauris sed quam ac nunc lacinia congue.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse a tortor a mauris luctus finibus eu sed mi. Integer scelerisque aliquam orci quis viverra. Nunc lobortis viverra semper. Curabitur hendrerit elit eget congue tincidunt. Curabitur sagittis blandit ex sed tincidunt. Nullam tellus diam, posuere at viverra a, varius sed nisi. In vel egestas nibh.', user_id: homer.id)

Comment.create(author: 'Jane Doe', content: 'My dog does the same thing.', article_id: cat.id, user_id: jane.id)
Comment.create(author: 'Carl Carlson', content: 'You sending some outgoing mail?', article_id: mail.id, user_id: carl.id)
Comment.create(author: 'Lenny Leonard', content: 'You know it.', article_id: mail.id, user_id: lenny.id)
Comment.create(author: 'Carl Carlson', content: "I'll probably send some tomorrow.", article_id: mail.id, user_id: carl.id)
Comment.create(author: 'Lenny Leonard', content: 'I hear that.', article_id: mail.id, user_id: lenny.id)
Comment.create(author: 'Jane Doe', content: "There's videos of cats on the internet now.", article_id: internet.id, user_id: jane.id)
Comment.create(author: 'Homer Simpson', content: 'Your ideas are intriguing to me and I wish to subscribe to your newsletter.', article_id: boy.id, user_id: homer.id)
Comment.create(author: 'Hank Hill', content: 'I like the cut of your jib.', article_id: pants.id, user_id: hank.id)
Comment.create(author: 'Homer Simpson', content: "What's a jib?", article_id: pants.id, user_id: homer.id)
Comment.create(author: "Carl Carlson", content: "You tell 'em Homer.", article_id: thermodynamics.id, user_id: homer.id)
Comment.create(author: 'John Doe', content: "Are you sure about that?", article_id: english.id, user_id: john.id)
Comment.create(author: 'Jane Doe', content: "Kids these days.", article_id: music.id, user_id: jane.id)
